[project]
name = "call-me-maybezo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "huggingface-hub>=0.34.0,<1.0",
    "llm-sdk>=1.0.1",
    "pydantic>=2.13.5",
    "torch>=2.13.0",
    "transformers>=4.57.3,<5.0.0",
]
[tool.uv.sources]
llm-sdk = { path = "./llm_sdk" }